version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.7
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.traefik-svc.loadbalancer.server.port=9999"
      - "traefik.docker.network=traefik_net_webhook"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.constraints=Label(`traefik.label`,`webhook-service`)
      - --entrypoints.webhook.address=:5001
      - --accesslog
      - --log
    networks:
      - traefik_net_webhook

  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webhook.service=webhook"
      - "traefik.http.services.webhook.loadbalancer.server.port=5001"
      - "traefik.http.routers.webhook.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.webhook.entrypoints=webhook"
      - "traefik.label=webhook-service"
      - "traefik.docker.network=traefik_net_webhook"
    env_file:
      - .env
    networks:
      - traefik_net_webhook

networks:
  traefik_net_webhook:
    external: true
